version: "3"
services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - '19807:3306'
    restart: always
    volumes:
      - /docker_strack/database/sql:/opt/sql
      - /docker_strack/database/shell:/docker-entrypoint-initdb.d
      - /docker_strack/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'strack'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      strack:
  redis:
    image: 'redis:5'
    restart: always
    command: redis-server --requirepass strack --appendonly yes
    ports:
      - '19806:6379'
    volumes:
      - /docker_strack/redis:/data
    networks:
      strack:
  rabbitmq:
    image: 'rabbitmq:management'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'strack'
      RABBITMQ_DEFAULT_PASS: 'strack'
    ports:
      - '19805:15672'
      - '19804:5672'
    networks:
      strack:
  centrifugo:
    image: 'centrifugo/centrifugo:v2.8'
    restart: always
    ports:
      - '19803:8000'
    command: centrifugo -c config.json
    volumes:
      - /docker_strack/centrifugo/config:/centrifugo
    networks:
      strack:
  strack_media:
    image: 'weijer/strack-media:latest'
    restart: always
    ports:
      - '19802:8080'
    depends_on:
      - rabbitmq
      - mysql
      - redis
    volumes:
      - /docker_strack/media/config:/app/config
    networks:
      strack:
  strack:
    image: 'weijer/strack-docker:latest'
    restart: always
    ports:
      - '19801:80'
    depends_on:
      - rabbitmq
      - mysql
      - redis
      - strack_media
      - centrifugo
    volumes:
      - /docker_strack/strack:/var/www
    networks:
      strack:
networks:
  strack:
