version: "3.7"
services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - /docker_test/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:5'
    restart: always
    command: redis-server --requirepass strack --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - /docker_test/redis:/data
  rabbitmq:
    image: 'rabbitmq:management'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'strack'
      RABBITMQ_DEFAULT_PASS: 'strack'
    ports:
      - '15672:15672'
      - '5672:5672'
  centrifugo:
    image: 'centrifugo/centrifugo:v2.8'
    restart: always
    ports:
      - '19803:8000'
    command: centrifugo -c config.json
    volumes:
      - /docker_test/centrifugo_config:/centrifugo
  strack_media:
    image: 'weijer/strack-media:latest'
    restart: always
    ports:
      - '19802:8080'
    depends_on:
      - rabbitmq
      - mysql
      - redis
    volumes:
      - /docker_test/media_config:/app/config
  strack:
    image: 'weijer/strack-docker:latest'
    restart: always
    ports:
      - '19801:80'
    depends_on:
      - rabbitmq
      - mysql
      - redis
      - strack_media
      - centrifugo
    volumes:
      - /docker_test/strack:/var/www
